### ISSUE TITLE
Syntax Error: invalid syntax

### ISSUE THREAD

**Issue by frankus** [sparkfun/Apollo3_Uploader_ASB#1]
I'm getting the following error when I run asb.py on my Mac (Python 2.7.15):

```
File "/Users/frank/Desktop/asb.py", line 380
    print('Connecting over serial port {}...'.format(args.port), flush=True)

Syntax Error: invalid syntax
```

**Comment by oclyke** [comment]
@frankus these scripts require python3, the invalid syntax comes from the difference between the ```print "string"``` syntax of Python2 and the ```print("string")``` syntax of Python3. Try installing Python3 and running the script as ```python3 asb.py [args]```. It should also be possible to run the script directly by relying on the ```#!/usr/bin/env python3``` shebang in the file (```./asby.py``` once python3 is installed)
